### ISSUE TITLE
Terminal configuration

### ISSUE THREAD

**Issue by bekhy** [stustapay/stustapay#264]
Good afternoon, I have a question about terminal I don't understand how to test it. 

Because when you open it, it says the error "no terminal configuration" 
There is a scanner in the settings, the configuration is loaded through it, as far as I understand. 
But where to get this particular setting? 
Or can make it download automatically, but I need "core_url" and "registration_uuid" 
But I also don’t understand where i can get them

**Comment by TheJJ** [comment]
you register the app to the core in its settings ("core connection"). this asks you to scan a qr code which is displayed by the administration ui when a terminal is not yet registered. the qr code contains all the infos a terminal needs to register and then fetch its settings via the terminalserver api.

**Comment by bekhy** [comment]
@TheJJ Good afternoon

There are problems with the terminal, it is not yet clear what exactly the reason is. The application seems to receive authorization, but then problems begin.
https://gist.github.com/NightSommelier/17634dd068ee2034fe30bd0a0e7ff83d

**Comment by TheJJ** [comment]
I think this query is failing for you:
```
            "select encode(key0, 'hex') as key0, encode(key1, 'hex') as key1 from user_tag_secret limit 1",
```

-> you need to store the nfc tag secret keys in the database in the `user_tag_secret` table. you can do that with the `load tag secret` cli.
