### ISSUE TITLE
Problem with stustapay db add-data

### ISSUE THREAD

**Issue by bekhy** [stustapay/stustapay#265]
![image](https://github.com/stustapay/stustapay/assets/79798507/da0a8acc-f711-455d-bbc9-674048df4d1b)

Tell me please why "stustapay db add-data" gives an error message? 

this is right after:
stustapay db rebuild

Obviously the problem is in NODE-ID. It is related to the secret key.

**Comment by bekhy** [comment]
![image](https://github.com/stustapay/stustapay/assets/79798507/840bdac7-b39e-4d03-8787-4c46159df08e)
We are missing a secret key and it should be added when we have a working node.

We have a node, a root node and an event node.
![image](https://github.com/stustapay/stustapay/assets/79798507/047a95a7-0d31-43fa-b52d-beb3304b298b)

**Comment by TheJJ** [comment]
i suggest you use stustaculum-2023 branch for now, since the node implementation is currently ongoing and out master branch is not yet stable with it. we will make sure that the transition from stustaculum-2023 branch to the master branch will work.

**Comment by bekhy** [comment]
@TheJJ 
Good afternoon
Launch error on branch 2023-stustaculum
![image](https://github.com/stustapay/stustapay/assets/79798507/f6561867-3620-479b-b8c9-f666544c0541)


Perhaps I'm doing something wrong, let you help me with the steps. Perhaps I missed something.

The error is due to the fact that there is no package launch file, that is, the main file __main__.py, there is only __init__.py in the folder. The main branch has a file __main__.py

Its main branch
![image](https://github.com/stustapay/stustapay/assets/79798507/c35bb731-c7f4-4f96-863e-087eaa26e39f)

This is stustaculum-2023
![image](https://github.com/stustapay/stustapay/assets/79798507/9135f294-2bc0-4ef6-ab91-01901a78f5ee)


I took this file from the main branch and checked it, but still an error
![image](https://github.com/stustapay/stustapay/assets/79798507/0a63e57e-8dfa-4127-a12f-253cd3d23fc9)



The error is clear to me, but is it even worth taking these dependencies from the main branch or is there another way?

**Comment by TheJJ** [comment]
probably not - the master is getting better in shape so you can try using it. but no promise, since we're adding new features providing more flexibility for merchants and product management.

**Comment by TheJJ** [comment]
We have more tree-related features on master now. I'll close this issue!
