### ISSUE TITLE
Problem with edit User and tag

### ISSUE THREAD

**Issue by bekhy** [stustapay/stustapay#270]
Good afternoon

1. There is nothing written in the logs about the error.
Please explain, there is a problem with editing users
![image](https://github.com/stustapay/stustapay/assets/79798507/80cc1f3f-03ae-40c1-9f3e-a10f90460c5b)
I have this problem 
![image](https://github.com/stustapay/stustapay/assets/79798507/9068c266-411a-4e4f-9b1f-e82e94ad05ac)

the project was assembled by npx nx build administration

But i found how can i resolve this:
1) i can edit roles 
![image](https://github.com/stustapay/stustapay/assets/79798507/f4d98c29-6f8f-449b-949f-93c1aefc7900)
2) after that i already can edit and users
![image](https://github.com/stustapay/stustapay/assets/79798507/f82e2f91-0cf8-46a3-a5e3-a91de47deb88)

2. I have tag, I added it to the db after that created a user with this UID
![image](https://github.com/stustapay/stustapay/assets/79798507/bf19aa53-e504-41c1-9107-ae9d13bc052c)

![image](https://github.com/stustapay/stustapay/assets/79798507/cd52c8b8-5e7a-461d-a0e6-2dd9856abbd7)

But when i try to check it (I bring the tag to the android with app), nothing happens
![image](https://github.com/stustapay/stustapay/assets/79798507/1f4c50bb-f739-4507-9e6f-1054699b4ea4)

What could be the problem?

**Comment by TheJJ** [comment]
What tag model do you have? How did you program it? Can you read it successfully with the NXP TagInfo App?

**Comment by bekhy** [comment]
@TheJJ 
![Изображение WhatsApp 2023-11-20 в 21 54 02_921b5947](https://github.com/stustapay/stustapay/assets/79798507/2de6c416-6a17-4287-8487-d7076d777176)
![Изображение WhatsApp 2023-11-20 в 21 53 17_b0c6ef53](https://github.com/stustapay/stustapay/assets/79798507/1a46d980-6c05-463e-aaa1-8725045d511c)
Its from that app

Are you using only of chip "Mifare Ultralight AES"? 
If yes, how can I combine this one too?


About how did i program it:
I added it to bd, and add user with UID from bd(i already add screenshots above)

**Comment by bekhy** [comment]
Good afternoon @TheJJ 

please tell me where I can find the part to add Other chip types? I cant found, or its on side android app?

**Comment by TheJJ** [comment]
https://github.com/stustapay/stustapay/tree/master/app%2Fapp%2Fsrc%2Fmain%2Fjava%2Fde%2Fstustapay%2Fstustapay%2Fnfc
This is the Ultralight AES code, and one would check the chip's type to use the variant code at scan-time.
You should use android studio to edit this.

**Comment by TheJJ** [comment]
I'll close this for now, since your cards are currently not implemented in the codebase. Feel free to open new issues if you encounter more problems.
