### ISSUE TITLE
Unable to create new event

### ISSUE THREAD

**Issue by tonowie** [stustapay/stustapay#410]
When I log in to admin portal I can use it without issues BUT when I try to create new event nothing happens on SUBMIT.

Steps to reproduce
1. select root node
2. settings -> create new event
3. General tab - fill in only mandatory data -> next
4. Customer portal - fill in some domains and email -> Next
5. SumUp - leave disabled -> Next
6. Bon - fill in some info -> Next
7. Email - leave email disabled -> Next
8. Payout - leave Payout disabled -> Submit

Nothing happens on submit, perhaps some data needs to be filled in to submit but forms do not indicate that? I do not see any errors in console and no endpoint is invoked

**Comment by tonowie** [comment]
running on last commit to repo 1c6777b1c709d19106d4f1ffc3c234d15ff090b9

**Comment by TheJJ** [comment]
are you in need of having an actually functional version? or do you plan on helping with development? or a mixture? 😀

the latest definitely functioning version is from this summer when we had our annual event. if the former is the case, you should use this version.

nevertheless should the current master branch state be fixed, so thanks for the report!

**Comment by tonowie** [comment]
mixed :) I want to start it up and get to understand it a bit. I will definitely contribute to documentation, not sure whether you will be interested in integrating my approach to deployment but it is definitely available as well :) as for contributing to the codebase I suck at python, react and kotlin so no plans there :D I can read it all though so perhaps one day... :)

**Comment by tonowie** [comment]
works like a charm! thank you
